name: 'Hardhat artifacts distribution action'
description:
  'Distribute the compilation artifacts of your Hardhat project to a target
  destination.'
author: 'VGLoic'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'upload-cloud'
  color: 'blue'

# Define your inputs here.
inputs:
  releaseName:
    description: 'Name of the release for the artifacts.'
    required: true
    default: 'latest'

# Define your outputs here.
outputs:
  hasDistributed:
    description: 'True if the artifacts have been distributed, false otherwise.'

runs:
  using: node20
  main: dist/index.js
